### ISSUE TITLE
Request - add a source for the lovely special effects shown in the docs

### ISSUE THREAD

**Issue by itamarcu** [Haxxer/FoundryVTT-Sequencer#1]
The [sample gifs](https://github.com/Haxxer/FoundryVTT-Sequencer/tree/master/docs/images) include some animations - "electrivity_blast_CIRCLE", "MagicMissile_01_Regular_{{color}}_30ft_0{{number}}_1600x400", etc.

Could you include a mention in the readme, crediting/linking the source for those special animations?

(because I'd love to see more stuff by that creator)

**Comment by Haxxer** [comment]
I added this just now :) Check near the top of the readme!
